x-ci-build: &ci-build
  context: ../
  platforms:
    - linux/amd64
    - linux/arm64
  args:
    BUILD_VERSION: ${TAG_VERSION}

services:
  ci-demo:
    container_name: ci-demo
    image: chaldea/ci-demo
    restart: always
    build:
      dockerfile: ./docker/Dockerfile
      tags:
        - chaldea/ci-demo:latest
        - chaldea/ci-demo:${DOCKER_TAG}
        - registry.cn-shanghai.aliyuncs.com/chaldea/ci-demo:latest
        - registry.cn-shanghai.aliyuncs.com/chaldea/ci-demo:${DOCKER_TAG}
      <<: *ci-build