x-ci-build: &ci-build
  context: ../
  platforms:
    - linux/amd64
    - linux/arm64
  args:
    BUILD_VERSION: 1.0.0

services:
  ci-demo:
    container_name: ci-demo
    image: chaldea/ci-demo
    restart: always
    build:
      dockerfile: ./docker/Dockerfile
      tags:
        - chaldea/ci-demo:latest
        - chaldea/ci-demo:${TAG_VERSION}
      <<: *ci-build