name: Package Testing

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
            artifact_name: demo1
            asset_name: demo1-linux-amd64
          # - os: windows-latest
          #   rid: win-x64
          #   artifact_name: demo1.exe
          #   asset_name: demo1-windows-amd64
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: dotnet publish ⚙
        run: |
          dotnet publish -r ${{ matrix.rid }} dotnet/demo1.csproj -o dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.API_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
