name: Package

on:
  push:
    branches:
      - 'docker'

env:
  VERSION: 1.0.1

jobs:
  docker:
    name: Create Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Compose Build
        working-directory: ./docker
        run: |
          echo "TAG_VERSION=${VERSION}" > .env
          cat .env
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
          echo "${{ secrets.DOCKER_ALIYUN_PASSWORD }}" | docker login -u ${{secrets.DOCKER_ALIYUN_USERNAME}} --password-stdin ${{secrets.DOCKER_ALIYUN_REPOSITORY}}
          docker compose build --push