name: Package

on:
  push:
    branches:
      - 'docker'

jobs:
  docker:
    name: Create Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Compose Build
        working-directory: ./docker
        run: |
          TAG_VERSION=1.0.1
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin ${{secrets.DOCKER_REPOSITORY}}
          echo ${TAG_VERSION}
          docker compose build --build-arg BUILD_VERSION=${TAG_VERSION} --push