name: Package

on:
  push:
    branches:
      - 'docker'

jobs:
  docker:
    name: Create Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Compose Build
        working-directory: ./docker
        run: |
          docker compose build --build-arg BUILD_VERSION=1.0.0 --push